# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CryptstreamTui < Formula
  desc "Live cryptocurrency ticker TUI — real-time Binance prices in your terminal"
  homepage "https://github.com/moneycaringcoder/cryptstream-tui"
  version "0.6.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moneycaringcoder/cryptstream-tui/releases/download/v0.6.4/cryptstream-tui_0.6.4_darwin_amd64.tar.gz"
      sha256 "901562cd20704445ab8494cf2e5c87264a41810a4817165d189a1d7507d45f20"

      define_method(:install) do
        bin.install "cryptstream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moneycaringcoder/cryptstream-tui/releases/download/v0.6.4/cryptstream-tui_0.6.4_darwin_arm64.tar.gz"
      sha256 "ca4ace2034ef17a3a4addceb31034b8751253e7d767f9570a72c82556394ad67"

      define_method(:install) do
        bin.install "cryptstream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/cryptstream-tui/releases/download/v0.6.4/cryptstream-tui_0.6.4_linux_amd64.tar.gz"
      sha256 "c47de632ddad35af4bebc1433633abe49645872ca1a572d80193ad16de4cf641"
      define_method(:install) do
        bin.install "cryptstream"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/cryptstream-tui/releases/download/v0.6.4/cryptstream-tui_0.6.4_linux_arm64.tar.gz"
      sha256 "2ba401b3379930f690bff411ed09b525fd84e2f7a477d0ab38487151f682e3a5"
      define_method(:install) do
        bin.install "cryptstream"
      end
    end
  end
end
