# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitstreamTui < Formula
  desc "Live GitHub activity feed TUI — watch repo events in your terminal"
  homepage "https://github.com/moneycaringcoder/gitstream-tui"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moneycaringcoder/gitstream-tui/releases/download/v0.3.0/gitstream-tui_0.3.0_darwin_amd64.tar.gz"
      sha256 "d4ce5ad2e46d9032ae1e8fc453f70cd2fd43dc7ab110994fa3173230d86a28d5"

      define_method(:install) do
        bin.install "gitstream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moneycaringcoder/gitstream-tui/releases/download/v0.3.0/gitstream-tui_0.3.0_darwin_arm64.tar.gz"
      sha256 "b140401c45978a7002c3a31aa41b33c6f2fbacd2d3709d3327a800c7fdcd0c4c"

      define_method(:install) do
        bin.install "gitstream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/gitstream-tui/releases/download/v0.3.0/gitstream-tui_0.3.0_linux_amd64.tar.gz"
      sha256 "c4f8d27e27d35796733f5a1ceb959d1102ff41b0a1410a099f41c5766e892b7e"
      define_method(:install) do
        bin.install "gitstream"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/gitstream-tui/releases/download/v0.3.0/gitstream-tui_0.3.0_linux_arm64.tar.gz"
      sha256 "42622a3a245011a83c357e2b93e7dacb89986e12a8e34e6ca999bca4482fcf8c"
      define_method(:install) do
        bin.install "gitstream"
      end
    end
  end
end
