# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitstreamTui < Formula
  desc "Live GitHub activity feed TUI — watch repo events in your terminal"
  homepage "https://github.com/moneycaringcoder/gitstream-tui"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moneycaringcoder/gitstream-tui/releases/download/v0.7.2/gitstream-tui_0.7.2_darwin_amd64.tar.gz"
      sha256 "269454001add1270c8de87243fe1ea20274d7a999a11c49cb3f1c1849a923085"

      define_method(:install) do
        bin.install "gitstream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moneycaringcoder/gitstream-tui/releases/download/v0.7.2/gitstream-tui_0.7.2_darwin_arm64.tar.gz"
      sha256 "dff86fffaf4dd4be122a5eb7d4d88ad3e3499dc7888ff35d8994e8df449355da"

      define_method(:install) do
        bin.install "gitstream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/gitstream-tui/releases/download/v0.7.2/gitstream-tui_0.7.2_linux_amd64.tar.gz"
      sha256 "421833205a86c314dd140398e8cbc1d999c203c9cabb649222e1f93d145735b7"
      define_method(:install) do
        bin.install "gitstream"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/gitstream-tui/releases/download/v0.7.2/gitstream-tui_0.7.2_linux_arm64.tar.gz"
      sha256 "bbd11992b6aec948176c15b16c525410db38727acedd1238d32bc2b684a79b1e"
      define_method(:install) do
        bin.install "gitstream"
      end
    end
  end
end
