# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitstreamTui < Formula
  desc "Live GitHub activity feed TUI — watch repo events in your terminal"
  homepage "https://github.com/moneycaringcoder/gitstream-tui"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moneycaringcoder/gitstream-tui/releases/download/v0.5.0/gitstream-tui_0.5.0_darwin_amd64.tar.gz"
      sha256 "2f6044eb5769e97c830671061e3af4d4d84de03e55cff7c0d8bcc6feab973638"

      define_method(:install) do
        bin.install "gitstream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moneycaringcoder/gitstream-tui/releases/download/v0.5.0/gitstream-tui_0.5.0_darwin_arm64.tar.gz"
      sha256 "06aa805d47e931e117565c1dac1fd929cdc67af0d58f2e23c66bb8312755e05a"

      define_method(:install) do
        bin.install "gitstream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/gitstream-tui/releases/download/v0.5.0/gitstream-tui_0.5.0_linux_amd64.tar.gz"
      sha256 "2fd1d12f71830ee482258d7f299072ae1d231ba6d8b5b700836f930ed344f3f8"
      define_method(:install) do
        bin.install "gitstream"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/gitstream-tui/releases/download/v0.5.0/gitstream-tui_0.5.0_linux_arm64.tar.gz"
      sha256 "7eff65517427f51889ac03890a059d56fa846cf564eb08eaebde7ae2fad5ffcf"
      define_method(:install) do
        bin.install "gitstream"
      end
    end
  end
end
