# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuitest < Formula
  desc "CLI runner for tuitest — the TUI testing framework in tuikit-go"
  homepage "https://github.com/moneycaringcoder/tuikit-go"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moneycaringcoder/tuikit-go/releases/download/v0.7.2/tuitest_0.7.2_darwin_amd64.tar.gz"
      sha256 "5806a168b745fee7f3ebcc95a276ba249d128540278d8dd18ff10471e3c6e1e6"

      define_method(:install) do
        bin.install "tuitest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moneycaringcoder/tuikit-go/releases/download/v0.7.2/tuitest_0.7.2_darwin_arm64.tar.gz"
      sha256 "a78d6985ac9049dc9f69a6af7c6bf282d3d828044e11d24595113d772b5fe1d3"

      define_method(:install) do
        bin.install "tuitest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/tuikit-go/releases/download/v0.7.2/tuitest_0.7.2_linux_amd64.tar.gz"
      sha256 "f6fc8de4e1459284151ffb645176a044aa74fced3e9ed9236dd67ef205cdf2e0"
      define_method(:install) do
        bin.install "tuitest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/tuikit-go/releases/download/v0.7.2/tuitest_0.7.2_linux_arm64.tar.gz"
      sha256 "48f5c97a97bc11db14247b0bc02f4557bb15076892b5b0c30019a1aa8f851efc"
      define_method(:install) do
        bin.install "tuitest"
      end
    end
  end

  test do
    system "#{bin}/tuitest", "-h"
  end
end
