# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuitest < Formula
  desc "CLI runner for tuitest — the TUI testing framework in tuikit-go"
  homepage "https://github.com/moneycaringcoder/tuikit-go"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moneycaringcoder/tuikit-go/releases/download/v0.10.0/tuitest_0.10.0_darwin_amd64.tar.gz"
      sha256 "7cf7779513896ea906100c37c058b72f8c80e799bd712839a82b64a4085c3138"

      define_method(:install) do
        bin.install "tuitest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moneycaringcoder/tuikit-go/releases/download/v0.10.0/tuitest_0.10.0_darwin_arm64.tar.gz"
      sha256 "d0c4ebb41bc414f8217ad0c5f823b8f10e3e84626006c8726fc80e6007079857"

      define_method(:install) do
        bin.install "tuitest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/tuikit-go/releases/download/v0.10.0/tuitest_0.10.0_linux_amd64.tar.gz"
      sha256 "d9a72612ea511b44b7b952ffd5b1c13f55b3de3be682b8b0908c0f555fddfebf"
      define_method(:install) do
        bin.install "tuitest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/tuikit-go/releases/download/v0.10.0/tuitest_0.10.0_linux_arm64.tar.gz"
      sha256 "e5b38c118f84804848674c3d0821b7965fbaf2ac5547953ad72d13c20e8f20a5"
      define_method(:install) do
        bin.install "tuitest"
      end
    end
  end

  test do
    system "#{bin}/tuitest", "-h"
  end
end
