# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuitest < Formula
  desc "CLI runner for tuitest — the TUI testing framework in tuikit-go"
  homepage "https://github.com/moneycaringcoder/tuikit-go"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moneycaringcoder/tuikit-go/releases/download/v0.9.0/tuitest_0.9.0_darwin_amd64.tar.gz"
      sha256 "2f15ab750e1737bc2c4a0784cd19c7e5081fa1909a717765a2e19bbc6d3d8f7e"

      define_method(:install) do
        bin.install "tuitest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moneycaringcoder/tuikit-go/releases/download/v0.9.0/tuitest_0.9.0_darwin_arm64.tar.gz"
      sha256 "3dbea5d6828dd134810d7a075fc23eb43d2b39e2b6e321fcf11388f7f201be7b"

      define_method(:install) do
        bin.install "tuitest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/tuikit-go/releases/download/v0.9.0/tuitest_0.9.0_linux_amd64.tar.gz"
      sha256 "6fe6166b380a660e2638275d65b73cbb570e1459fbec8ae49812d9f2236311d4"
      define_method(:install) do
        bin.install "tuitest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moneycaringcoder/tuikit-go/releases/download/v0.9.0/tuitest_0.9.0_linux_arm64.tar.gz"
      sha256 "c90826eaa7ac670afa65e816431090cd630e048d6f266b1d1bec3bb4feb1614a"
      define_method(:install) do
        bin.install "tuitest"
      end
    end
  end

  test do
    system "#{bin}/tuitest", "-h"
  end
end
